# Generated by Django 4.2.5 on 2023-09-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_step_description_alter_tool_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='step',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tool_related_step', to='base.step'),
        ),
    ]
