# Generated by Django 4.2.5 on 2023-09-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_tool_step_remove_tool_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='base.step')),
            ],
        ),
    ]
