# Generated by Django 4.2.5 on 2023-09-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_stepgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_step', to='base.step')),
            ],
        ),
        migrations.DeleteModel(
            name='StepGoal',
        ),
    ]
