# Generated by Django 4.2.5 on 2023-09-28 11:08

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_subtask_delete_substep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': [django.db.models.functions.comparison.Cast('step_number', output_field=models.IntegerField())]},
        ),
    ]
