# Generated by Django 4.2.5 on 2023-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_step_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='description',
        ),
    ]
