# Generated by Django 4.2.5 on 2023-10-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_step_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='base.step'),
        ),
    ]
