# Generated by Django 4.2.5 on 2023-10-26 09:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_subtask_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='step', editable=False, populate_from='title'),
        ),
    ]
