# Generated by Django 4.2.5 on 2023-10-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_step_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='slug',
        ),
    ]
