# Generated by Django 4.2.5 on 2023-11-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_subtask_related_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='related_tool',
            new_name='related_tools',
        ),
    ]
