# Generated by Django 4.2.5 on 2023-09-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='step',
            new_name='related_step',
        ),
    ]
