# Generated by Django 4.2.5 on 2023-09-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_rename_step_tool_related_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='related_step',
        ),
    ]
