# Generated by Django 4.2.5 on 2023-09-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_stepgoal'),
        ('tools', '0003_remove_tool_related_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='step',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_vuln_related_step', to='base.step'),
        ),
    ]
