# Generated by Django 4.2.5 on 2023-10-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_subtask_step'),
        ('tools', '0004_tool_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='step',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tool_related_step', to='base.step'),
        ),
    ]
